### ISSUE TITLE
Detecting whether a function has implicit `None` returns

### ISSUE THREAD

**Issue by tusharsadhwani** [JelleZijlstra/autotyping#62]
Basic control flow can be implemented to remove all false positive cases where implicit `None` return may happen.

### The strategy
- visiting `If`, `While` and `For` nodes, to find all control flow paths inside a function definition.
- If any of the paths don't terminate with a `return` or `raise` (or something like `exit()` or `sys.exit()`), we assume that the function can return implicitly.
- Adding another flag, `seen_implicit_none_return` to state, and storing the information there.

If it sounds good, I can try and implement exactly this.

**Comment by JelleZijlstra** [comment]
I'm not enthusiastic about this because I want autotyping to remain a simple tool, not a type inference engine. I already help maintain two type checkers (pyanalyze and mypy) and that's plenty. Specifically the "or something like exit() or sys.exit()" information: doing that right requires us to look in typeshed or annotations to figure out which functions return Never.
